#!/bin/sh
set -e
lb config noauto \
    --mode debian \
    --distribution bookworm \
    --architectures amd64 \
    --binary-images iso-hybrid \
    --debian-installer false \
    --archive-areas "main contrib non-free non-free-firmware" \
    --apt-recommends true \
    --bootappend-live "boot=live components username=live user-fullname=Live autologin"
